[workspace]
resolver = "2"
members = [
    "tidewave-core",
    "tidewave-cli",
    "src-tauri", "phoenix-rs",
]

[workspace.package]
version = "0.3.3"

[patch.crates-io]
# TODO: upstream
tao = { git = "https://github.com/wojtekmach/tao.git", branch = "wm-bundled-activation-policy" }
